name: Build

on: push

jobs:
  build-win:
    name: Build for Windows
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install build tools
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: mingw-w64-x86_64-clang mingw-w64-x86_64-pkg-config autotools
    - name: Checkout adaptagrams
      uses: actions/checkout@v3
      with:
        repository: mjwybrow/adaptagrams
        ref: fcac991f9f7d959e8326ae0567ce122839fbd4be
        path: adaptagrams
    - name: Configure and compile libavoid
      working-directory: ${{ github.workspace }}/adaptagrams/cola
      run: |
        mkdir -p m4
        autoreconf --install
        ./configure --disable-shared
        cd libavoid; make
    - name: Checkout libavoid-server
      uses: actions/checkout@v3
      with:
        path: libavoid-server
    - name: Compile libavoid-server
      working-directory: ${{ github.workspace }}/libavoid-server
      run: make win LIBAVOID=$GITHUB_WORKSPACE/adaptagrams/cola
    - name: Upload executable binary
      uses: actions/upload-artifact@v3
      with:
        name: libavoid-server-win.exe
        path: ${{ github.workspace }}/libavoid-server/bin/libavoid-server-win.exe

  build-macos:
    name: Build for macOS
    runs-on: macos-11
    steps:
    - name: Install build tools
      run: brew install automake libtool pkg-config
    - name: Checkout adaptagrams
      uses: actions/checkout@v3
      with:
        repository: mjwybrow/adaptagrams
        ref: fcac991f9f7d959e8326ae0567ce122839fbd4be
        path: adaptagrams
    - name: Configure and compile libavoid
      working-directory: ${{ github.workspace }}/adaptagrams/cola
      run: |
        mkdir -p m4
        autoreconf --install
        ./configure
        cd libavoid; make
    - name: Checkout libavoid-server
      uses: actions/checkout@v3
      with:
        path: libavoid-server
    - name: Compile libavoid-server
      working-directory: ${{ github.workspace }}/libavoid-server
      run: make macos LIBAVOID=$GITHUB_WORKSPACE/adaptagrams/cola
    - name: Upload executable binary
      uses: actions/upload-artifact@v3
      with:
        name: libavoid-server-macos
        path: ${{ github.workspace }}/libavoid-server/bin/libavoid-server-macos

  build-Linux:
    name: Build for Linux
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout adaptagrams
      uses: actions/checkout@v3
      with:
        repository: mjwybrow/adaptagrams
        ref: fcac991f9f7d959e8326ae0567ce122839fbd4be
        path: adaptagrams
    - name: Configure and compile libavoid
      working-directory: ${{ github.workspace }}/adaptagrams/cola
      run: |
        mkdir -p m4
        autoreconf --install
        ./configure
        cd libavoid; make
    - name: Checkout libavoid-server
      uses: actions/checkout@v3
      with:
        path: libavoid-server
    - name: Compile libavoid-server
      working-directory: ${{ github.workspace }}/libavoid-server
      run: make linux LIBAVOID=$GITHUB_WORKSPACE/adaptagrams/cola
    - name: Upload executable binary
      uses: actions/upload-artifact@v3
      with:
        name: libavoid-server-linux
        path: ${{ github.workspace }}/libavoid-server/bin/libavoid-server-linux
